version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: dentist-postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dentist
    ports:
      - "5433:5432"
    volumes: 
      - ./persistence-data:/var/lib/postgresql/data

volumes:  
  pgdata:
